language: cpp

os: linux

cache: ccache

dist: xenial

# build only master branch
branches:
  only:
    - master

jobs:
  include:
    - env: VERSION=8 BITS=64
      compiler: gcc
    - env: VERSION=8 BITS=32
      compiler: gcc
    - env: VERSION=7 BITS=32
      compiler: gcc
    - env: VERSION=3.8 BITS=32
      compiler: clang

before_install:
  - ./travis.sh before_install

before_script:
  - ./travis.sh before_script

script:
  - ./travis.sh script

after_success:
  - ./travis.sh after_success
