name: 🐧 Linux Builds

on:
  push:
    branches-ignore:
      - "l10n_master"
  pull_request:
    branches:
      - master

jobs:
  build_linux_qt:
    name: "AppImage"
    if: github.repository != 'PCSX2/pcsx2' || github.event_name == 'pull_request'
    uses: ./.github/workflows/linux_build_qt.yml
    with:
      jobName: "Qt"
      compiler: clang
      cmakeflags: ""
      buildAppImage: true
    secrets: inherit
  build_linux_flatpak:
    name: "Flatpak"
    if: github.repository != 'PCSX2/pcsx2' || github.event_name == 'pull_request'
    uses: ./.github/workflows/linux_build_flatpak.yml
    with:
      jobName: "Qt"
      compiler: clang
      cmakeflags: ""
      publish: false
